#python visualize.py --eps 0.0001 --to-show samples
#python visualize.py --eps 0.001 --to-show samples
#python visualize.py --eps 0.01 --to-show samples
#python visualize.py --eps 0.0001 --to-show histogram
#python visualize.py --eps 0.001 --to-show histogram
#python visualize.py --eps 0.01 --to-show histogram
python visualize.py --eps 0.0001 --to-show statistics
python visualize.py --eps 0.001 --to-show statistics
python visualize.py --eps 0.01 --to-show statistics
